spring:
  main:
    lazy-initialization: false
    web-application-type: servlet
    banner-mode: off
  lifecycle:
    timeout-per-shutdown-phase: 60s
  jackson:
    time-zone: UTC
    locale: en_US
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://postgres-prod:5432/notification-dev"
    username: "user"
    password: "P@55w0rd"
    hikari:
      minimumIdle: 1
      maximumPoolSize: 3
      autoCommit: false
      connectionTestQuery: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        default_schema: "notification"
  flyway:
    enabled: true
    locations: "classpath:db/migration"
    url: "jdbc:postgresql://postgres-prod:5432/notification-dev"
    username: "user"
    password: "P@55w0rd"
    schemas: "notification"
  kafka:
    consumer:
      bootstrap-servers: http://kafka-prod:9092
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: notification-events-listener-group
    template:
      default-topic: notification-event
    listener:
      ack-mode: manual

server:
  port: 8084
  shutdown: graceful
  servlet:
    session:
      timeout: 60m
      cookie:
        http-only: true
    application-display-name: kafka-consumer
  compression:
    enabled: true
    min-response-size: 2KB
    mime-types: "text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json, application/xml, image/jpeg, image/png, application/octet-stream"
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org.springframework: debug
    org.springframework.cloud: debug
    com.kafka.consumer.demo: debug