spring:
  datasource:
    url: "jdbc:postgresql://postgres-prod:5432/notification-dev"
  flyway:
    enabled: true
    url: "jdbc:postgresql://postgres-prod:5432/notification-dev"
  kafka:
    bootstrap-servers: http://kafka-prod-1:29092, http://kafka-prod-2:29092, http://kafka-prod-3:29092