spring:
  datasource:
    url: "jdbc:postgresql://postgres:5432/notification-dev"
  flyway:
    enabled: true
    url: "jdbc:postgresql://postgres:5432/notification-dev"
  kafka:
    bootstrap-servers: http://kafka-1:29092, http://kafka-2:29092, http://kafka-3:29092
