spring:
  kafka:
    bootstrap-servers: http://kafka-1:29092, http://kafka-2:29092, http://kafka-3:29092
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:80"
              - "http://prod-default:80"
              - "http://web-prod:80"
      routes:
        - id: notification-service
          uri: http://web:8080 # or producer-prod:8083
          predicates:
            - Path=/api/notifications/**
            - Header=X-CSRF-TOKEN, [0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}
            - Host=**web**
          filters:
            - name: NotificationPreFilter
            - name: NotificationPostFilter