server:
  port: 8082
  shutdown: graceful

spring:
  main:
    banner-mode: off
  lifecycle:
    timeout-per-shutdown-phase: 60s
  zipkin:
    kafka:
      topic: zipkin
    sender:
      type: KAFKA
  kafka:
    bootstrap-servers: http://localhost:9092, http://localhost:9093, http://localhost:9094
    listener:
      missing-topics-fatal: false
  thymeleaf:
    enabled: false
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - POST
              - PUT
              - OPTIONS
      routes:
        - id: notification-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/notifications/**
            - Header=X-CSRF-TOKEN, [0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}
          filters:
            - name: NotificationPreFilter
            - name: NotificationPostFilter

logging:
  level:
    org.springframework: trace
