spring:
  main:
    lazy-initialization: false
    web-application-type: servlet
    banner-mode: off
  jackson:
    time-zone: UTC
    locale: en_US
  mvc:
    format:
      date: iso
      date-time: iso
  lifecycle:
    timeout-per-shutdown-phase: 60s
  kafka:
    producer:
      bootstrap-servers: http://kafka:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all # default value 1, To turn off set 0.
      retries: 10 # positive integer is possible. Max 2147483647.
    admin:
      properties:
        bootstrap-servers: http://kafka:9092
        linger:
          ms: 1
        retries: 5
    template:
      default-topic: notification-event

server:
  port: 8083
  shutdown: graceful
  servlet:
    session:
      timeout: 60m
      cookie:
        http-only: true
    application-display-name: kafka-producer
  compression:
    enabled: true
    min-response-size: 2KB # default value
    mime-types: "text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json, application/xml, image/jpeg, image/png, application/octet-stream"
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org.springframework: info
    org.springframework.cloud: info
    com.kafka.producer.demo: debug
